### PR TITLE
Many fixes and improvements

### PR DESCRIPTION
**Pull request by petronny**
1. set `CUDA_VISIBLE_DEVICES` in environment instead of `SGE_ROOT`
This variable is popularly used in tensorflow and pytorch.
1. <s>use file lock instead of directory lock
It seems that SGE is using directory lock.
But I think file lock is more popular in linux systems.</s>
1. source settings.sh in prolog
Inspired by https://github.com/kageback/sge-gpuprolog/commit/e615f58519471cfc802a3e13e846cad550b22c83
1. fix exit codes
See http://www.softpanorama.org/HPC/Grid_engine/prolog_and_epilog_scripts.shtml
1. removed lock file when failed
From #2

### CODE REVIEW

**Comment by kyamagu** [comment]
Thanks, but `mkdir` is for ensuring atomicity. See https://unix.stackexchange.com/questions/70/what-unix-commands-can-be-used-as-a-semaphore-lock

**Comment by petronny** [comment]
> Thanks, but mkdir is for ensuring atomicity. See https://unix.stackexchange.com/questions/70/what-unix-commands-can-be-used-as-a-semaphore-lock

I see. I will drop that commit.

**Comment by petronny** [comment]
> I will drop that commit.

Done

**Comment by kyamagu** [comment]
Great, thanks!

**Pull request merged**
